# Generated by Django 3.0.8 on 2020-07-09 11:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
